version: '3.1'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    volumes: 
      - '/mnt/hard/data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 1234
    ports: 
      - 5432:5432