version: '3.1'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    volumes: 
      - './postgres-data:/var/lib/postgresql'
    environment:
      POSTGRES_PASSWORD: 1234
    ports: 
      - 5432:5432